# Generated by Django 3.2.4 on 2021-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=20)),
                ('last_name', models.CharField(default=None, max_length=20)),
                ('age', models.PositiveSmallIntegerField(default=None)),
                ('date_of_birth', models.DateField(default=None)),
                ('student_id', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default=None, max_length=10)),
                ('nationality', models.CharField(default=None, max_length=20)),
                ('course', models.CharField(blank=True, max_length=30, null=True)),
                ('admission_date', models.DateField(auto_now=True, null=True)),
                ('student_image', models.ImageField(default=None, upload_to='images/')),
                ('room_no', models.CharField(blank=True, max_length=15, null=True)),
                ('medical_report', models.FileField(default=None, upload_to='files/')),
                ('student_phonenumber', models.CharField(default=None, max_length=15)),
                ('class_name', models.CharField(default=None, max_length=10)),
                ('academical_year', models.CharField(default='2021', max_length=5)),
                ('gurdian_name', models.CharField(default=None, max_length=50)),
                ('gurdian_phonenumber', models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
