# Generated by Django 3.2.4 on 2021-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='gurdian_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='gurdian_phonenumber',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_report',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='room_no',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phonenumber',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
    ]
