# Generated by Django 3.2.4 on 2021-07-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='student',
            name='academical_year',
            field=models.DateField(default=None),
        ),
    ]
