# Generated by Django 3.2.4 on 2021-07-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210730_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academical_year',
            field=models.DateField(),
        ),
    ]
