# Generated by Django 3.2.4 on 2021-07-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_academical_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
