# Generated by Django 3.2.4 on 2021-08-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academical_year',
            field=models.DateField(default='2010-10-10'),
        ),
    ]
