# Generated by Django 3.2.4 on 2021-08-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_academical_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academical_year',
            field=models.DateField(),
        ),
    ]
