# Generated by Django 3.2.4 on 2021-08-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_academical_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academical_year',
            field=models.CharField(default='2021', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
