# Generated by Django 3.2.4 on 2021-08-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20210808_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
