# Generated by Django 3.2.4 on 2021-08-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=10)),
                ('course_channel', models.CharField(max_length=20)),
                ('trainer', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('course_email', models.EmailField(default=0, max_length=254)),
                ('syllabus', models.CharField(max_length=20)),
            ],
        ),
    ]
