# Generated by Django 3.2.4 on 2021-08-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_date', models.DateTimeField()),
                ('start_And_end', models.TimeField()),
                ('venue', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('event_link', models.CharField(max_length=50)),
            ],
        ),
    ]
