# Generated by Django 3.2.4 on 2021-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('national_id', models.CharField(default=None, max_length=15)),
                ('contract', models.FileField(upload_to='files/')),
                ('resume', models.FileField(upload_to='files/')),
                ('salary', models.PositiveBigIntegerField()),
                ('trainer_image', models.ImageField(default=None, upload_to='images/')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default=None, max_length=10)),
                ('phonenumber', models.CharField(default=None, max_length=15)),
                ('syllabus_relationship', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=5)),
                ('company', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
