# Generated by Django 3.2.4 on 2021-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='company',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='contract',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='course',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='course_code',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='course_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='joining_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='resume',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.PositiveBigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='syllabus_relationship',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
