# Generated by Django 3.2.4 on 2021-08-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20210813_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
